package com.epbt2.common.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * StdMenu Value Object.
  * This class is value object representing database table MPLN.STD_MENU
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class StdMenu implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String menuGroupId;
    private String menuDesc;
    private String menuApplType;
    private String menuCall;
    private String menuSeq;
    private String menuId;
    private String nameSpace;
    private String actionLink;
    private String webControl;
    private String webSeq;
    private String webApplType;
    private String webMenuCall;
    
    /* BYE 18/07/2014 */
    private String menuIcon;
    private String menuMainId;
    private String menuMainDesc;
    private String menuMainGroup;
    private String menuIconSts;
    private String projectName;

    public String getMenuIcon() {
        return menuIcon;
    }

    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    public String getMenuMainId() {
        return menuMainId;
    }

    public void setMenuMainId(String menuMainId) {
        this.menuMainId = menuMainId;
    }

    public String getMenuMainDesc() {
        return menuMainDesc;
    }

    public void setMenuMainDesc(String menuMainDesc) {
        this.menuMainDesc = menuMainDesc;
    }

    public String getMenuMainGroup() {
        return menuMainGroup;
    }

    public void setMenuMainGroup(String menuMainGroup) {
        this.menuMainGroup = menuMainGroup;
    }

    public String getMenuIconSts() {
        return menuIconSts;
    }

    public void setMenuIconSts(String menuIconSts) {
        this.menuIconSts = menuIconSts;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    /* BYE 18/07/2014 */

    /* BYE 29/11/2014 */
    private int bilNotify;

    public int getBilNotify() {
        return bilNotify;
    }

    public void setBilNotify(int bilNotify) {
        this.bilNotify = bilNotify;
    }    
    /* BYE 29/11/2014 */

    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public StdMenu () {

    }

    public StdMenu (String menuGroupIdIn) {

          this.menuGroupId = menuGroupIdIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getMenuGroupId() {
          return this.menuGroupId;
    }
    public void setMenuGroupId(String menuGroupIdIn) {
          this.menuGroupId = menuGroupIdIn;
    }

    public String getMenuDesc() {
          return this.menuDesc;
    }
    public void setMenuDesc(String menuDescIn) {
          this.menuDesc = menuDescIn;
    }

    public String getMenuApplType() {
          return this.menuApplType;
    }
    public void setMenuApplType(String menuApplTypeIn) {
          this.menuApplType = menuApplTypeIn;
    }

    public String getMenuCall() {
          return this.menuCall;
    }
    public void setMenuCall(String menuCallIn) {
          this.menuCall = menuCallIn;
    }

    public String getMenuSeq() {
          return this.menuSeq;
    }
    public void setMenuSeq(String menuSeqIn) {
          this.menuSeq = menuSeqIn;
    }

    public String getMenuId() {
          return this.menuId;
    }
    public void setMenuId(String menuIdIn) {
          this.menuId = menuIdIn;
    }

    public String getNameSpace() {
          return this.nameSpace;
    }
    public void setNameSpace(String nameSpaceIn) {
          this.nameSpace = nameSpaceIn;
    }

    public String getActionLink() {
          return this.actionLink;
    }
    public void setActionLink(String actionLinkIn) {
          this.actionLink = actionLinkIn;
    }

    public String getWebControl() {
          return this.webControl;
    }
    public void setWebControl(String webControlIn) {
          this.webControl = webControlIn;
    }

    public String getWebSeq() {
          return this.webSeq;
    }
    public void setWebSeq(String webSeqIn) {
          this.webSeq = webSeqIn;
    }

    public String getWebApplType() {
          return this.webApplType;
    }
    public void setWebApplType(String webApplTypeIn) {
          this.webApplType = webApplTypeIn;
    }

    public String getWebMenuCall() {
          return this.webMenuCall;
    }
    public void setWebMenuCall(String webMenuCallIn) {
          this.webMenuCall = webMenuCallIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String menuGroupIdIn,
          String menuDescIn,
          String menuApplTypeIn,
          String menuCallIn,
          String menuSeqIn,
          String menuIdIn,
          String nameSpaceIn,
          String actionLinkIn,
          String webControlIn,
          String webSeqIn,
          String webApplTypeIn,
          String webMenuCallIn) {
          this.menuGroupId = menuGroupIdIn;
          this.menuDesc = menuDescIn;
          this.menuApplType = menuApplTypeIn;
          this.menuCall = menuCallIn;
          this.menuSeq = menuSeqIn;
          this.menuId = menuIdIn;
          this.nameSpace = nameSpaceIn;
          this.actionLink = actionLinkIn;
          this.webControl = webControlIn;
          this.webSeq = webSeqIn;
          this.webApplType = webApplTypeIn;
          this.webMenuCall = webMenuCallIn;
    }


    /** 
     * hasEqualMapping-method will compare two StdMenu instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(StdMenu valueObject) {

          if (this.menuGroupId == null) {
                    if (valueObject.getMenuGroupId() != null)
                           return(false);
          } else if (!this.menuGroupId.equals(valueObject.getMenuGroupId())) {
                    return(false);
          }
          if (this.menuDesc == null) {
                    if (valueObject.getMenuDesc() != null)
                           return(false);
          } else if (!this.menuDesc.equals(valueObject.getMenuDesc())) {
                    return(false);
          }
          if (this.menuApplType == null) {
                    if (valueObject.getMenuApplType() != null)
                           return(false);
          } else if (!this.menuApplType.equals(valueObject.getMenuApplType())) {
                    return(false);
          }
          if (this.menuCall == null) {
                    if (valueObject.getMenuCall() != null)
                           return(false);
          } else if (!this.menuCall.equals(valueObject.getMenuCall())) {
                    return(false);
          }
          if (this.menuSeq == null) {
                    if (valueObject.getMenuSeq() != null)
                           return(false);
          } else if (!this.menuSeq.equals(valueObject.getMenuSeq())) {
                    return(false);
          }
          if (this.menuId == null) {
                    if (valueObject.getMenuId() != null)
                           return(false);
          } else if (!this.menuId.equals(valueObject.getMenuId())) {
                    return(false);
          }
          if (this.nameSpace == null) {
                    if (valueObject.getNameSpace() != null)
                           return(false);
          } else if (!this.nameSpace.equals(valueObject.getNameSpace())) {
                    return(false);
          }
          if (this.actionLink == null) {
                    if (valueObject.getActionLink() != null)
                           return(false);
          } else if (!this.actionLink.equals(valueObject.getActionLink())) {
                    return(false);
          }
          if (this.webControl == null) {
                    if (valueObject.getWebControl() != null)
                           return(false);
          } else if (!this.webControl.equals(valueObject.getWebControl())) {
                    return(false);
          }
          if (this.webSeq == null) {
                    if (valueObject.getWebSeq() != null)
                           return(false);
          } else if (!this.webSeq.equals(valueObject.getWebSeq())) {
                    return(false);
          }
          if (this.webApplType == null) {
                    if (valueObject.getWebApplType() != null)
                           return(false);
          } else if (!this.webApplType.equals(valueObject.getWebApplType())) {
                    return(false);
          }
          if (this.webMenuCall == null) {
                    if (valueObject.getWebMenuCall() != null)
                           return(false);
          } else if (!this.webMenuCall.equals(valueObject.getWebMenuCall())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass StdMenu, mapping to table MPLN.STD_MENU\n");
        out.append("Persistent attributes: \n"); 
        out.append("menuGroupId = " + this.menuGroupId + "\n"); 
        out.append("menuDesc = " + this.menuDesc + "\n"); 
        out.append("menuApplType = " + this.menuApplType + "\n"); 
        out.append("menuCall = " + this.menuCall + "\n"); 
        out.append("menuSeq = " + this.menuSeq + "\n"); 
        out.append("menuId = " + this.menuId + "\n"); 
        out.append("nameSpace = " + this.nameSpace + "\n"); 
        out.append("actionLink = " + this.actionLink + "\n"); 
        out.append("webControl = " + this.webControl + "\n"); 
        out.append("webSeq = " + this.webSeq + "\n"); 
        out.append("webApplType = " + this.webApplType + "\n"); 
        out.append("webMenuCall = " + this.webMenuCall + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        StdMenu cloned = new StdMenu();

        if (this.menuGroupId != null)
             cloned.setMenuGroupId(new String(this.menuGroupId)); 
        if (this.menuDesc != null)
             cloned.setMenuDesc(new String(this.menuDesc)); 
        if (this.menuApplType != null)
             cloned.setMenuApplType(new String(this.menuApplType)); 
        if (this.menuCall != null)
             cloned.setMenuCall(new String(this.menuCall)); 
        if (this.menuSeq != null)
             cloned.setMenuSeq(new String(this.menuSeq)); 
        if (this.menuId != null)
             cloned.setMenuId(new String(this.menuId)); 
        if (this.nameSpace != null)
             cloned.setNameSpace(new String(this.nameSpace)); 
        if (this.actionLink != null)
             cloned.setActionLink(new String(this.actionLink)); 
        if (this.webControl != null)
             cloned.setWebControl(new String(this.webControl)); 
        if (this.webSeq != null)
             cloned.setWebSeq(new String(this.webSeq)); 
        if (this.webApplType != null)
             cloned.setWebApplType(new String(this.webApplType)); 
        if (this.webMenuCall != null)
             cloned.setWebMenuCall(new String(this.webMenuCall)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}